# Generated by Django 4.2.27 on 2026-03-09 06:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'purchasing_suppliers',
                'ordering': ['supplier_name', 'supplier_id'],
                'indexes': [models.Index(fields=['supplier_name'], name='purchasing__supplie_b6fcd4_idx'), models.Index(fields=['phone'], name='purchasing__phone_36adfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(db_index=True)),
                ('amount_ton', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('density', models.DecimalField(decimal_places=4, help_text='Fuel density in kilograms per liter.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Purchase price per ton.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Latest exchange rate from purchase currency to base currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('total_amount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total purchase amount in the purchase currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount_in_base_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total purchase amount converted to the base currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paid_currency_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Derived exchange rate from paid currency to purchase currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount_in_purchase_currency_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paid amount converted into the purchase currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount_in_base_currency_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paid amount converted into the base currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('remaining_amount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining amount in the purchase currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_amount_in_base_currency_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining amount in the base currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='financial.currency')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.fuel')),
                ('paid_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_paid_amounts', to='financial.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='employees.partners')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchasing.supplier')),
            ],
            options={
                'db_table': 'purchasing_purchases',
                'ordering': ['-purchase_date', '-purchase_id'],
                'indexes': [models.Index(fields=['purchase_date'], name='purchasing__purchas_554261_idx'), models.Index(fields=['supplier', 'purchase_date'], name='purchasing__supplie_f66171_idx'), models.Index(fields=['partner', 'purchase_date'], name='purchasing__partner_84b620_idx'), models.Index(fields=['currency'], name='purchasing__currenc_62d29d_idx'), models.Index(fields=['paid_currency'], name='purchasing__paid_cu_003ccd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderPurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.PositiveIntegerField(db_index=True, default=0, help_text='Automatically assigned order number.')),
                ('amount_per_ton', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('density', models.DecimalField(decimal_places=4, help_text='Fuel density in kilograms per liter.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price per ton.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Latest exchange rate from order currency to base currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('currency_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated order cost converted to the base currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_order_purchases', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_purchases', to='financial.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_purchases', to='purchasing.supplier')),
                ('tanker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_purchases', to='inventory.tankstorage')),
            ],
            options={
                'db_table': 'purchasing_order_purchases',
                'ordering': ['-date', '-order_purchase_id'],
                'indexes': [models.Index(fields=['order_id'], name='purchasing__order_i_ba244e_idx'), models.Index(fields=['supplier', 'date'], name='purchasing__supplie_a8b08a_idx'), models.Index(fields=['tanker', 'date'], name='purchasing__tanker__cd219b_idx'), models.Index(fields=['currency'], name='purchasing__currenc_2a795b_idx')],
            },
        ),
    ]
