# Generated by Django 4.2.27 on 2026-03-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(max_length=125)),
                ('type', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'Feul',
                'unique_together': {('fuel_name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='TankStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_number', models.IntegerField()),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=200)),
                ('min_level_alert', models.IntegerField()),
                ('Fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fuel')),
            ],
            options={
                'db_table': 'Tank_Storage',
                'unique_together': {('Fuel', 'tank_number')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fuel')),
            ],
            options={
                'db_table': 'Price_history',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase_in', 'purchase_In'), ('sale_out', 'Sale Out'), ('lending_out', 'Lending out'), ('return_in', 'Return in'), ('adjustment', 'Adjustment')], max_length=125)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(choices=[('sale', 'Sale'), ('lending', 'Lendin'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], max_length=125)),
                ('reference_id', models.PositiveSmallIntegerField()),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('fuel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fuel')),
                ('tank_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tankstorage')),
            ],
            options={
                'db_table': 'Inventory_transaction',
            },
        ),
        migrations.CreateModel(
            name='FuelMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_name', models.CharField(max_length=100)),
                ('fuel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fuel')),
                ('tank_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tankstorage')),
            ],
            options={
                'db_table': 'Motors',
                'unique_together': {('tank_id', 'fuel_id')},
            },
        ),
    ]
