# Generated by Django 4.2.27 on 2026-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_fuelmotor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='adjustment_direction',
            field=models.CharField(blank=True, choices=[('in', 'In'), ('out', 'Out')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='reference_id',
            field=models.PositiveIntegerField(),
        ),
    ]
