# Generated by Django 4.2.27 on 2026-03-09 06:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sale_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount_in_base_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='financial.currency')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.fuel')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.fuelmotor')),
            ],
            options={
                'db_table': 'sales_sales',
                'ordering': ['-sale_date', '-sale_id'],
                'indexes': [models.Index(fields=['sale_date'], name='sales_sales_sale_da_93351e_idx'), models.Index(fields=['fuel', 'sale_date'], name='sales_sales_fuel_id_4abd6d_idx'), models.Index(fields=['motor', 'sale_date'], name='sales_sales_motor_i_d72af2_idx'), models.Index(fields=['currency'], name='sales_sales_currenc_577b27_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lending_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_amount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='unpaid', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='employees.customer')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='inventory.fuel')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guaranteed_lendings', to='employees.customer')),
            ],
            options={
                'db_table': 'sales_lendings',
                'ordering': ['-sale_date', '-lending_id'],
                'indexes': [models.Index(fields=['customer', 'sale_date'], name='sales_lendi_custome_24b38b_idx'), models.Index(fields=['fuel', 'sale_date'], name='sales_lendi_fuel_id_70b0c5_idx'), models.Index(fields=['guarantor'], name='sales_lendi_guarant_0e7201_idx'), models.Index(fields=['end_date'], name='sales_lendi_end_dat_111ddb_idx'), models.Index(fields=['status'], name='sales_lendi_status_f2c768_idx')],
            },
        ),
    ]
