# Generated by Django 4.2.27 on 2026-03-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransaction_adjustment_direction_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='tank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='inventory.tankstorage'),
        ),
        migrations.AddIndex(
            model_name='lending',
            index=models.Index(fields=['tank_id', 'sale_date'], name='sales_lendi_tank_id_5683fe_idx'),
        ),
    ]
