# Generated by Django 4.2.27 on 2026-03-09 06:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('father_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('mean_address', models.CharField(max_length=255)),
                ('current_address', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Join_date', models.DateField()),
            ],
            options={
                'db_table': 'Partners',
                'unique_together': {('first_name', 'father_name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=150)),
                ('last_name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'customer_profiles',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='customer_pr_first_n_f91fa1_idx'), models.Index(fields=['total_purchases'], name='customer_pr_total_p_1a2599_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('father_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('work_days', models.TextField(default='[]')),
                ('join_date', models.DateField()),
                ('membership_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیر فعال')], db_index=True, default='active', max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=employees.models.employee_picture_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'indexes': [models.Index(fields=['status'], name='employees_status_0192ac_idx'), models.Index(fields=['membership_type'], name='employees_members_5b2bab_idx'), models.Index(fields=['join_date'], name='employees_join_da_8f8d98_idx')],
            },
        ),
    ]
