# Generated by Django 4.2.27 on 2026-03-09 06:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('exchange', 'Exchange')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'finance_accounts',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('is_base', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'finance_currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pay_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='employees.employee')),
            ],
            options={
                'db_table': 'finance_salaries',
                'ordering': ['-pay_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount_money', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Remaining: 0.00', max_length=128)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_partner_debts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_debts', to='financial.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='employees.partners')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_partner_debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_debts',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_time', models.DateTimeField(db_index=True)),
                ('reference_type', models.CharField(blank=True, choices=[('sales', 'فروشات'), ('purchase', 'خرید'), ('Expense', 'مصارف'), ('lending_payment', 'دریافت قرض'), ('salary', 'معاش'), ('Exchange', 'صرافی')], max_length=100, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_financial_transactions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='financial.currency')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_financial_transactions', to='financial.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_financial_transactions', to='financial.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_financial_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_financial_transactions',
                'ordering': ['-date_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_in_base_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pay_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='financial.currency')),
            ],
            options={
                'db_table': 'finance_expenses',
                'ordering': ['-pay_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rate_value', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('date', models.DateField(db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_currency_rates', to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='financial.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='financial.currency')),
            ],
            options={
                'db_table': 'finance_currency_rates',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('is_base',), name='finance_currency_single_base'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='financial.currency'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'year', 'month'], name='finance_sal_employe_b6b57a_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['pay_date'], name='finance_sal_pay_dat_8e47dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='finance_salary_employee_year_month_unique'),
        ),
        migrations.AddIndex(
            model_name='partnerdebt',
            index=models.Index(fields=['partner', 'date'], name='partner_deb_partner_c06223_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdebt',
            index=models.Index(fields=['currency'], name='partner_deb_currenc_029560_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdebt',
            index=models.Index(fields=['status'], name='partner_deb_status_cf42c9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type', 'date_time'], name='finance_fin_transac_7ed7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['currency', 'date_time'], name='finance_fin_currenc_4e314c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['from_account', 'date_time'], name='finance_fin_from_ac_380d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['to_account', 'date_time'], name='finance_fin_to_acco_140ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['pay_date'], name='finance_exp_pay_dat_745b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['title'], name='finance_exp_title_655d53_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['from_currency', 'to_currency', 'date'], name='finance_cur_from_cu_4db3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['date'], name='finance_cur_date_fcf723_idx'),
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date'), name='finance_currency_rate_unique_pair_date'),
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.CheckConstraint(check=models.Q(('from_currency', models.F('to_currency')), _negated=True), name='finance_currency_rate_from_to_diff'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name'], name='finance_acc_name_d1e62e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='finance_acc_account_b6788a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'currency')},
        ),
    ]
