# Generated by Django 4.2.27 on 2026-03-10 01:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('amount_paid_in_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'partner_debt_payments',
                'ordering': ['-paid_date', '-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ['-date', '-created_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='currencyrate',
            name='finance_currency_rate_unique_pair_date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='partnerdebt',
            name='currency_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='partnerdebtpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_partner_debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerdebtpayment',
            name='currency_paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_debt_payments', to='financial.currency'),
        ),
        migrations.AddField(
            model_name='partnerdebtpayment',
            name='partner_debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.partnerdebt'),
        ),
        migrations.AddIndex(
            model_name='partnerdebtpayment',
            index=models.Index(fields=['partner_debt', 'paid_date'], name='partner_deb_partner_a2d161_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdebtpayment',
            index=models.Index(fields=['currency_paid'], name='partner_deb_currenc_39aec1_idx'),
        ),
    ]
